parameters:
  buildConfiguration: ''

steps:
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/MongoDelta.csproj;**/MongoDelta.AspNetCore3.csproj'
    configuration: '${{ parameters.buildConfiguration }}'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '4'
    patchVersion: '0'
  displayName: 'Create NuGet Package'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'df1cab1e-21bf-4a8e-a335-29d7a5b730ab/ebdc565b-a6c5-4e3b-b9e7-f666a31340ec'
  displayName: 'Push NuGet Package'