parameters:
  buildConfiguration: ''

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration ${{ parameters.buildConfiguration }} --collect:"XPlat Code Coverage"'
  displayName: 'Run Unit Tests'