trigger: none
pr: none
  
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- template: templates/environment-setup-steps.yml
  parameters:
    solution: $(solution)
    
- template: templates/build-steps.yml
  parameters:
    solution: $(solution)
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    
- task: ChocolateyCommand@0
  inputs:
    command: 'install'
    installPackageId: 'mongodb.portable'
  displayName: 'Install MongoDb and Run'

- task: CmdLine@2
  inputs:
    script: 'mkdir "$(Build.ArtifactStagingDirectory)/BenchmarkArtifacts"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: '**/MongoDelta.Benchmarking/*.csproj'
    arguments: '-c Release -- -f * -a "$(Build.ArtifactStagingDirectory)/BenchmarkArtifacts"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/BenchmarkArtifacts'
    ArtifactName: 'Benchmark Results'
    publishLocation: 'Container'