trigger: none
pr: none
  
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'CI'

steps:

- template: templates/environment-setup-steps.yml
  parameters:
    solution: $(solution)
    
- template: templates/build-steps.yml
  parameters:
    solution: $(solution)
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    

