trigger: none

pr:
  branches:
    include:
      - master
      
schedules:
- cron: "0 0 * * *"
  displayName: "Nightly Build"
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'CI'

steps:

- template: templates/environment-setup-steps.yml
  parameters:
    solution: $(solution)
    
- template: templates/build-steps.yml
  parameters:
    solution: $(solution)
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    
- template: templates/unit-test-steps.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
    
- template: templates/integration-test-steps.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
    
- template: templates/publish-test-results-steps.yml
  parameters:
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)

- template: templates/publish-code-coverage-steps.yml

- template: templates/prerelease-nuget-steps.yml
  parameters:
    buildConfiguration: $(buildConfiguration)